name: Update underlying JSSM

on:
  workflow_call:
    inputs:
      libversion:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - env: 
        LIBVERSION: ${{ inputs.libversion }}
      run: 
        eval 'echo "Should update lib to $LIBVERSION here"'
