name: Update underlying JSSM

on: [repository_dispatch]

jobs:
  remote-invoked-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 16 for remote build
      if: github.event.action == 'upgrade_jssm'
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Remote-build 
      if: github.event.action == 'upgrade_jssm'
      run: |
        echo "should upgrade to '"$"' "
      env:
        GITHUB_REPOSITORY: ${{ github.event.lib_version }}
