name: Node CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        include:
          - node-version: 23.x   # fastest, so run first, to error fast
            os: ubuntu-latest
          - node-version: 23.x   # slowest, so run next. sort by slowest from here to get earliest end through parallelism
            os: macos-latest
          - node-version: 13.x   # finish check big-3 on latest current
            os: windows-latest
          - node-version: 14.x  # lastly check just ubuntu on historic node versions because speed, oldest (slowest) first
            os: ubuntu-latest
          - node-version: 15.x
            os: ubuntu-latest
          - node-version: 16.x
            os: ubuntu-latest
          - node-version: 17.x
            os: ubuntu-latest
          - node-version: 18.x
            os: ubuntu-latest
          - node-version: 19.x
            os: ubuntu-latest
          - node-version: 20.x
            os: ubuntu-latest
          - node-version: 21.x
            os: ubuntu-latest
          - node-version: 22.x
            os: ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install && npm run build
      env:
        CI: true
