name: Node CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        node-version: [8.x, 13.x]
        node-version: ['macos-latest', 'windows-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
      env:
        CI: true
